/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRouteWithContext } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VisitImport } from './routes/visit'
import { Route as ServicesImport } from './routes/services'
import { Route as NewsImport } from './routes/news'
import { Route as MapImport } from './routes/map'
import { Route as InvestorsImport } from './routes/investors'
import { Route as EcosystemImport } from './routes/ecosystem'
import { Route as DiscoverImport } from './routes/discover'
import { Route as BrandsImport } from './routes/brands'
import { Route as BranchesImport } from './routes/branches'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DiningIndexImport } from './routes/dining.index'
import { Route as EventsSlugImport } from './routes/events.$slug'

// Create/Update Routes

const VisitRoute = VisitImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const NewsRoute = NewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const InvestorsRoute = InvestorsImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRoute,
} as any)

const EcosystemRoute = EcosystemImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRoute,
} as any)

const DiscoverRoute = DiscoverImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRoute,
} as any)

const BrandsRoute = BrandsImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRoute,
} as any)

const BranchesRoute = BranchesImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DiningIndexRoute = DiningIndexImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSlugRoute = EventsSlugImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesImport
      parentRoute: typeof rootRoute
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsImport
      parentRoute: typeof rootRoute
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverImport
      parentRoute: typeof rootRoute
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemImport
      parentRoute: typeof rootRoute
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitImport
      parentRoute: typeof rootRoute
    }
    '/dining/': {
      id: '/dining/'
      path: '/dining/'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/dining/': typeof DiningIndexRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/dining': typeof DiningIndexRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/dining/': typeof DiningIndexRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/branches' | '/brands' | '/discover' | '/ecosystem' | '/investors' | '/map' | '/news' | '/services' | '/visit' | '/dining/' | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/branches' | '/brands' | '/discover' | '/ecosystem' | '/investors' | '/map' | '/news' | '/services' | '/visit' | '/dining' | '/events/$slug'
  id: '__root__' | '/' | '/about' | '/branches' | '/brands' | '/discover' | '/ecosystem' | '/investors' | '/map' | '/news' | '/services' | '/visit' | '/dining/' | '/events/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRoute
  BrandsRoute: typeof BrandsRoute
  DiscoverRoute: typeof DiscoverRoute
  EcosystemRoute: typeof EcosystemRoute
  InvestorsRoute: typeof InvestorsRoute
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
  VisitRoute: typeof VisitRoute
  DiningIndexRoute: typeof DiningIndexRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AboutRoute,
  BranchesRoute,
  BrandsRoute,
  DiscoverRoute,
  EcosystemRoute,
  InvestorsRoute,
  MapRoute,
  NewsRoute,
  ServicesRoute,
  VisitRoute,
  DiningIndexRoute,
  EventsSlugRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
