/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as MapRouteImport } from './routes/map'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BranchesIdRouteImport } from './routes/branches.$id'
import { Route as DiningIndexRouteImport } from './routes/dining.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BranchesRoute,
} as any)
const BranchesIdRoute = BranchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BranchesRoute,
} as any)
const DiningIndexRoute = DiningIndexRouteImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRouteWithChildren
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/branches/$id': typeof BranchesIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/branches/': typeof BranchesIndexRoute
  '/dining/': typeof DiningIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/branches/$id': typeof BranchesIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/branches': typeof BranchesIndexRoute
  '/dining': typeof DiningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRouteWithChildren
  '/brands': typeof BrandsRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/visit': typeof VisitRoute
  '/branches/$id': typeof BranchesIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/branches/': typeof BranchesIndexRoute
  '/dining/': typeof DiningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/brands'
    | '/discover'
    | '/ecosystem'
    | '/investors'
    | '/map'
    | '/news'
    | '/services'
    | '/visit'
    | '/branches/$id'
    | '/events/$slug'
    | '/branches/'
    | '/dining/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/discover'
    | '/ecosystem'
    | '/investors'
    | '/map'
    | '/news'
    | '/services'
    | '/visit'
    | '/branches/$id'
    | '/events/$slug'
    | '/branches'
    | '/dining'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/brands'
    | '/discover'
    | '/ecosystem'
    | '/investors'
    | '/map'
    | '/news'
    | '/services'
    | '/visit'
    | '/branches/$id'
    | '/events/$slug'
    | '/branches/'
    | '/dining/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  DiscoverRoute: typeof DiscoverRoute
  EcosystemRoute: typeof EcosystemRoute
  InvestorsRoute: typeof InvestorsRoute
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
  VisitRoute: typeof VisitRoute
  EventsSlugRoute: typeof EventsSlugRoute
  DiningIndexRoute: typeof DiningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/branches/$id': {
      id: '/branches/$id'
      path: '/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof BranchesIdRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/dining/': {
      id: '/dining/'
      path: '/dining'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BranchesRouteChildren {
  BranchesIdRoute: typeof BranchesIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesIdRoute: BranchesIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRouteWithChildren,
  BrandsRoute: BrandsRoute,
  DiscoverRoute: DiscoverRoute,
  EcosystemRoute: EcosystemRoute,
  InvestorsRoute: InvestorsRoute,
  MapRoute: MapRoute,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRoute,
  VisitRoute: VisitRoute,
  EventsSlugRoute: EventsSlugRoute,
  DiningIndexRoute: DiningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
