/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MapRouteImport } from './routes/map'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as DiningIndexRouteImport } from './routes/dining.index'
import { Route as DiningSlugRouteImport } from './routes/dining.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningIndexRoute = DiningIndexRouteImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningSlugRoute = DiningSlugRouteImport.update({
  id: '/dining/$slug',
  path: '/dining/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/entertainment': typeof EntertainmentRoute
  '/investors': typeof InvestorsRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/visit': typeof VisitRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/dining/': typeof DiningIndexRoute
  '/events/': typeof EventsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/entertainment': typeof EntertainmentRoute
  '/investors': typeof InvestorsRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/visit': typeof VisitRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/dining': typeof DiningIndexRoute
  '/events': typeof EventsIndexRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/entertainment': typeof EntertainmentRoute
  '/investors': typeof InvestorsRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/visit': typeof VisitRoute
  '/dining/$slug': typeof DiningSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/dining/': typeof DiningIndexRoute
  '/events/': typeof EventsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/entertainment'
    | '/investors'
    | '/locations'
    | '/map'
    | '/offers'
    | '/visit'
    | '/dining/$slug'
    | '/events/$slug'
    | '/stores/$slug'
    | '/dining/'
    | '/events/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/entertainment'
    | '/investors'
    | '/locations'
    | '/map'
    | '/offers'
    | '/visit'
    | '/dining/$slug'
    | '/events/$slug'
    | '/stores/$slug'
    | '/dining'
    | '/events'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/entertainment'
    | '/investors'
    | '/locations'
    | '/map'
    | '/offers'
    | '/visit'
    | '/dining/$slug'
    | '/events/$slug'
    | '/stores/$slug'
    | '/dining/'
    | '/events/'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  EcosystemRoute: typeof EcosystemRoute
  EntertainmentRoute: typeof EntertainmentRoute
  InvestorsRoute: typeof InvestorsRoute
  LocationsRoute: typeof LocationsRoute
  MapRoute: typeof MapRoute
  OffersRoute: typeof OffersRoute
  VisitRoute: typeof VisitRoute
  DiningSlugRoute: typeof DiningSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  StoresSlugRoute: typeof StoresSlugRoute
  DiningIndexRoute: typeof DiningIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining/': {
      id: '/dining/'
      path: '/dining'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining/$slug': {
      id: '/dining/$slug'
      path: '/dining/$slug'
      fullPath: '/dining/$slug'
      preLoaderRoute: typeof DiningSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  EcosystemRoute: EcosystemRoute,
  EntertainmentRoute: EntertainmentRoute,
  InvestorsRoute: InvestorsRoute,
  LocationsRoute: LocationsRoute,
  MapRoute: MapRoute,
  OffersRoute: OffersRoute,
  VisitRoute: VisitRoute,
  DiningSlugRoute: DiningSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  StoresSlugRoute: StoresSlugRoute,
  DiningIndexRoute: DiningIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
